FROM python:3.13.3-bookworm

WORKDIR /app

COPY requirements.txt .
COPY entrypoint.sh .
RUN chmod 777 entrypoint.sh && pip install --no-cache-dir -r requirements.txt

COPY ./app .
ENTRYPOINT ["./entrypoint.sh"]